# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


**答**
- list(a) 只會沿著 ndarray 的第一個 dimension 轉換，因此只有第一層會變成 list (最外層的[])
- a.tolist() 會把整個 ndarray 轉換成多維的 list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
# 記得先 Import 正確的套件

import numpy as np

In [34]:

a = np.random.randint(10, size=6) 


print(a)
print(a.ndim)    # a 是一維陣列 ndim=1
print(a.shape)   # a 的大小是 6x1
print(a.size)    # a 總共有 6個 element
print(a.dtype)   # a 的每個元素是都是 int32
print(a.itemsize)  # a 的每個元素是都是 int32, int32 是 4 byte
print(a.shape[0])  # a 的寬度是 shape 的第一個元素 
print(type(a))     # a 是一個 ndarray


[8 5 4 3 2 2]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)    # b 是二維陣列 ndim=2
print(b.shape)   # b 的大小是 3x4
print(b.size)    # b 總共有 3x4 = 12個 element
print(b.dtype)   # b 的每個元素是都是 int32
print(b.itemsize)  # b 的每個元素是都是 int32, int32 是 4 byte
print(b.shape[0])  # b 的寬度是 shape 的第一個元素 
print(type(b))     # b 是一個 ndarray


[[8 9 7 0]
 [6 8 3 8]
 [2 7 3 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)    # c 是三維陣列 ndim=3
print(c.shape)   # c 的大小是 2x3x2
print(c.size)    # c 總共有 2x3x2 = 12個 element
print(c.dtype)   # c 的每個元素是都是 int32
print(c.itemsize)  # c 的每個元素是都是 int32, int32 是 4 byte
print(c.shape[0])  # c 的寬度是 shape 的第一個元素 
print(type(c))     # c 是一個 ndarray


[[[0 5]
  [7 4]
  [3 7]]

 [[6 9]
  [5 1]
  [5 3]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [22]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 9, 5, 1, 3, 7]
[6, 9, 5, 1, 3, 7]


In [23]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[2, 0, 6, 6], [7, 7, 5, 9], [9, 2, 6, 9]]
[array([2, 0, 6, 6]), array([7, 7, 5, 9]), array([9, 2, 6, 9])]


In [10]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 3], [2, 8], [3, 2]], [[3, 4], [7, 6], [0, 6]]]
[array([[7, 3],
       [2, 8],
       [3, 2]]), array([[3, 4],
       [7, 6],
       [0, 6]])]


In [35]:
# 用遞迴方式實做，
# 當輸入的陣列超過一維的時候，把每一個 row 分別轉成 list 再組成新的 list
# 當輸入陣列只剩一維時，回傳轉成 list 的 array

def tolist(iterable):
    if iterable.ndim == 1:
        return list(iterable)
    else:
        y = []
        for i in range(iterable.shape[0]):
            y.append(tolist(iterable[i]))
        return y      
        
print(tolist(a))
print(tolist(b))
print(tolist(c))


[8, 5, 4, 3, 2, 2]
[[2, 0, 6, 6], [7, 7, 5, 9], [9, 2, 6, 9]]
[[[7, 3], [2, 8], [3, 2]], [[3, 4], [7, 6], [0, 6]]]
